name: expenses
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  admob_flutter: ^0.3.4
  charts_flutter: ^0.9.0
  modern_charts: ^0.1.19
  pie_chart: ^3.1.1
  sqflite: ^0.11.1
  path_provider: ^0.4.1
  font_awesome_flutter: ^8.8.1
  provider: ^4.0.4
  intl: ^0.16.1
  shared_preferences: ^0.5.6+3
  flutter_launcher_icons: "^0.8.0"
  numberpicker: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/UBUNTU-M.TTF
        - asset: fonts/UBUNTU-B.TTF
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: fonts/OpenSans-Italic.ttf
          weight: 400
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600


  
    # - family: RobotoMono
    #   fonts:
    #     - asset: fonts/RobotoMono-Regular.ttf
    #     - asset: fonts/RobotoMono-Bold.ttf
    #       weight: 700
